### ISSUE TITLE
How do i fix the red x

### ISSUE THREAD

**Issue by Nonethousand** [Trenavix/SM64Paint#5]
when i try to open super mario 64 from it says, "Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click Quit, the application will close immediately. \n\nIndex was outside of the bounds array."
When I click continue it just shows a red x

**Comment by SKCro** [comment]
You need to extend your SM64 ROM file. You can't use an unmodified ROM.
